networks:
  dev:
    driver: bridge

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=notes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - dev
  server-dotnet:
    image: notes/server-dotnet
    container_name: server-dotnet
    restart: always
    build:
      context: ./server-dotnet
      dockerfile: Dockerfile
    environment:
      - Database__TestSource=Server=db; User ID=root; Password=root; Database=notes
      - Security__TestHosts=http://localhost:5070
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev
  client: 
    image: notes/client
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "5070:80"
    depends_on:
      - server-dotnet
